name: Docker Release CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up docker environment
        run: echo "DOCKER_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag nylonee/watchlistarr:${DOCKER_TAG}
      - name: Push Docker image
        run: |
          docker tag nylonee/watchlistarr:${DOCKER_TAG} nylonee/watchlistarr:latest
          docker push nylonee/watchlistarr:${DOCKER_TAG}
          docker push nylonee/watchlistarr:latest
          steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Check for dependency updates
        run: sbt dependencyUpdatesFailBuild
      - name: Check for unused dependencies
        run: sbt unusedCompileDependenciesTest
      - name: Check for transitive dependencies
        run: sbt undeclaredCompileDependenciesTest
      - name: Run tests
        run: sbt test
      - name: Build fat JAR
        run: sbt assembly
      - name: Upload JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/scala-2.13/watchlistarr-assembly-0.1.0-SNAPSHOT.jar
          asset_name: watchlistarr-assembly-0.1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive
