name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Check for dependency updates
      run: sbt dependencyUpdatesFailBuild
    - name: Check for unused dependencies
      run: sbt unusedCompileDependenciesTest
    - name: Check for transitive dependencies
      run: sbt undeclaredCompileDependenciesTest
    - name: Run tests
      run: sbt test
